# Generated by Django 4.2.7 on 2023-11-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='performance',
            field=models.PositiveIntegerField(default=1, help_text='От 1 до 12'),
        ),
    ]
