# Generated by Django 4.2.7 on 2023-11-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('1', '1-й курс'), ('2', '2-й курс'), ('3', '3-й курс')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='instrument',
            field=models.CharField(choices=[('Пианино', 'Пианино'), ('Гитара', 'Гитара'), ('Скрипка', 'Скрипка')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='performance',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=255),
        ),
    ]
